In [40]:
import numpy as np 

vector = [
    [[110,200,300],[101,200,300],[103,200,300]],
    [[150,200,300],[10,200,300],[90,200,300]],
    [[80,200,300],[100,200,300],[100,200,300]]
]

array = np.array(vector)

# print(array)


[[110 200 300]
 [101 200 300]
 [103 200 300]]


In [38]:
array[:,:,0]

array([[110, 101, 103],
       [150,  10,  90],
       [ 80, 100, 100]])