## Matriz


Una matriz es una tabla rectangular o tabla bidimensional que consta de m filas y n columnas (el tamaño se escribe como m x n). Las matrices generalmente se denotan con letras latinas mayúsculas, por ejemplo, A. Sus elementos están en minúsculas con doble índice a_ij, donde i es el número de fila y j es el número de columna.

#### Creando una matriz a partir de dos vectores


In [ ]:
import pandas as pd
import numpy as np

vector1= np.array([1,2,3])
vector2= np.array([4,5,6])

matrix = np.array([vector1 , vector2])
matrix

#### Crear una matriz a partir de un df

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'a': [120, 60, 75], 'b': [42, 154, 90],'c': [1344, 154, 2090] })
print(df)
matrix = df.values
matrix

     a    b     c
0  120   42  1344
1   60  154   154
2   75   90  2090


array([[ 120,   42, 1344],
       [  60,  154,  154],
       [  75,   90, 2090]], dtype=int64)

Otra operación útil que podríamos necesitar realizar es acceder a un elemento de la matriz. Usando la matriz A en el código anterior, el elemento a_ij se llama mediante A[i, j], donde la fila es i y la columna es j, enumeradas desde cero, de la misma forma que los índices de matriz.

Veamos esto en el siguiente ejemplo donde recuperamos el elemento de matriz 2090:

In [ ]:
matrix[2,2]

2090

In [ ]:
matrix[[0,2],:]

array([[ 120,   42, 1344],
       [  75,   90, 2090]], dtype=int64)

#### Atributos para matrices

In [39]:
matrix.shape
matrix.argmax() #posicion de fila (vector) donde se encuentra el valor mas alto
matrix.argmin() #posicion de fila (vector) se encuentra el valor mas bajo
matrix.argsort() #ordena y devuelve los indices evaluando y ordenando los números por filas (es mas facil verlo en un df porque ve el valor mas bajo de una fila)
matrix.astype(float) #transforma los tipos de datos
matrix.cumsum() #suma cumulativa.
matrix.cumprod() # va multiplicando por cada valor en los vectores.
matrix.diagonal() # da los valores de las diagonales.
matrix.max() #valor maximo de la matriz
matrix.min() # valor minimo de la matriz
matrix.mean() # valor total promedio.
matrix.repeat(2) # Repite todos los valores.
matrix.prod() #producto de la multiplicacione de todos los elementos en la matriz
matrix.sum() #suma todo los valores
matrix.std() #obtiene la variacion std
matrix.transpose() #transpone los datos
matrix.T #transponer

array([[1, 4],
       [2, 5],
       [3, 6]])

### Operaciones con matrices.

#### Operaciones de matrices por un numero

In [ ]:
import numpy as np

matrix = np.array([
    [1, 2], 
    [3, 4]])

print(f' product \n{matrix * 2}', end='\n\n')
print(f' sum \n{matrix + 2}', end='\n\n')
print(f' rest \n{matrix - 2}', end='\n\n')

 product 
[[2 4]
 [6 8]]

 sum 
[[3 4]
 [5 6]]

 rest 
[[-1  0]
 [ 1  2]]



#### Operaciones de matrices con otras matrices.

In [ ]:
import numpy as np

matrix1 = np.array([
    [1, 2], 
    [3, 4]])

matrix2 = np.array([
    [5, 6], 
    [7, 8]])

print(f'product \n{np.multiply(matrix1, matrix2)}', end='\n\n') 
print(f'sum \n{matrix1 + matrix2}', end='\n') 
print(f'rest \n{matrix1 - matrix2}', end='\n')

product 
[[ 5 12]
 [21 32]]

sum 
[[ 6  8]
 [10 12]]
rest 
[[-4 -4]
 [-4 -4]]


In [ ]:
import numpy as np
import pandas as pd

services = ['Minutos', 'Mensajes', 'Megabytes']

monday = np.array([
    [10, 2, 72],
    [3, 5, 111],
    [15, 3, 50],
    [27, 0, 76],
    [7, 1, 85]])

tuesday = np.array([
    [33, 0, 108],
    [21, 5, 70],
    [15, 2, 15],
    [29, 6, 34],
    [2, 1, 146]])

wednesday = np.array([
    [16, 0, 20],
    [23, 5, 34],
    [5, 0, 159],
    [35, 1, 74],
    [5, 0, 15]])

thursday = np.array([
    [25, 1, 53],
    [15, 0, 26],
    [10, 0, 73],
    [18, 1, 24],
    [2, 2, 24]])

friday = np.array([
    [32, 0, 33],
    [4, 0, 135],
    [2, 2, 21],
    [18, 5, 56],
    [27, 2, 21]])

saturday = np.array([
    [28, 0, 123],
    [16, 5, 165],
    [10, 1, 12],
    [42, 4, 80],
    [18, 2, 20]])

sunday = np.array([
    [30, 4, 243],
    [18, 2, 23],
    [12, 2, 18],
    [23, 0, 65],
    [34, 0, 90]])

weekly = np.array(monday + tuesday + wednesday + thursday + friday + saturday + sunday)

print('En una semana')
print(pd.DataFrame(weekly, columns=services))
print()

## cuánto usa cada cliente los servicios en promedio por día
## crear una matris con todos los días

forecast = ((weekly / 7) * 30.4).astype(int)

print('Pronóstico para un mes')
print(pd.DataFrame(forecast, dtype=int, columns=services))

En una semana
   Minutos  Mensajes  Megabytes
0      174         7        652
1      100        22        564
2       69        10        348
3      192        17        409
4       95         8        401

Pronóstico para un mes
   Minutos  Mensajes  Megabytes
0      755        30       2831
1      434        95       2449
2      299        43       1511
3      833        73       1776
4      412        34       1741


#### Operacion de matrices por un vector

Para entender exactamente cómo se multiplica una matriz por un vector, primero debemos recordar que una matriz no es más que un conjunto de vectores de la misma longitud.

$$ 
\begin{matrix}a_{11} & a_{12} & \cdots & a_{1n} \\a_{21} & a_{22} & \cdots & a_{2n} \\\vdots & \vdots & \ddots & \vdots \\a_{m1} & a_{m2} & \cdots & a_{mn} \\\end{matrix}\begin{pmatrix}x_1 \\x_2 \\\vdots \\x_n \\\end{pmatrix}=\begin{pmatrix}a_{11}x_1 + a_{12}x_2 + \cdots + a_{1n}x_n \\a_{21}x_1 + a_{22}x_2 + \cdots  a_{2n}x_n \\\vdots \\a_{m1}x_1 + a_{m2}x_2 + \cdots + a_{mn}x_n \\\end{pmatrix}$$

Ya conocemos el uso del producto escalar para multiplicar un vector por otro. El mismo principio guía este proceso también. Para multiplicar una matriz por un vector, tomamos el producto escalar de cada fila y el vector, como puedes ver a continuación. El resultado es un nuevo vector. Sin embargo, presta atención: ya que estamos usando el producto escalar, es esencial que la longitud de cada fila de la matriz sea igual a la longitud del vector por el que multiplicamos.

La mejor parte es que NumPy puede encargarse de todo esto por nosotros. Todo lo que tenemos que hacer es llamar a dot(). Podemos hacer esto como una función independiente o como un método de nuestra matriz.

In [11]:
import numpy as np

matrix = np.array([
    [1,2,3],
    [4,5,6]])

vector = np.array([3,3,3])

# Funcion independiente, toma dos argumentos
print(np.dot(matrix,vector))

# Funcion de la matriz- solo necesita un argumento
print(matrix.dot(vector))

[18 45]
[18 45]


Calcula la cantidad de minutos, mensajes de texto y tráfico de Internet gastados por el segundo cliente en el transcurso del mes. Guarda el resultado en la variable client_services y muéstralo en la pantalla (ya en el precódigo).

In [24]:
import numpy as np
import pandas as pd

services = ['Minutos', 'Mensajes', 'Megabytes']
packs_names = ['"Al volante"', '"En el metro"']
packs = np.array([[20, 5], [2, 5], [500, 1000]])
clients_packs = np.array([[1, 2], [2, 3], [4, 1], [2, 3], [5, 0]])

df= pd.DataFrame(packs, columns=packs_names, index=services)
df

"Al volante"  "En el metro"
Minutos              20              5
Mensajes              2              5
Megabytes           500           1000

In [27]:
clients_df = pd.DataFrame(clients_packs, columns=packs_names)
clients_df

"Al volante"  "En el metro"
0             1              2
1             2              3
2             4              1
3             2              3
4             5              0

In [29]:
print("Paquete del cliente")
print(pd.DataFrame(clients_packs[1], index=packs_names, columns=['']))
print()


Paquete del cliente
                
"Al volante"   2
"En el metro"  3



In [35]:
client_vector = clients_packs[1]
client_services= df.values.dot(client_vector)

print('Minutos', 'Mensajes', 'Megabytes')
print(client_services)

Minutos Mensajes Megabytes
[  55   19 4000]


In [36]:
import numpy as np
import pandas as pd

services = ['Minutos', 'Mensajes', 'Megabytes']
packs_names = ['"Al volante"', '"En el metro"']
packs = np.array([[20, 5], [2, 5], [500, 1000]])

clients_packs = np.array([[1, 2], [2, 3], [4, 1], [2, 3], [5, 0]])

print("Paquete del cliente")
print(pd.DataFrame(clients_packs[1], index=packs_names, columns=['']))
print()

client_vector = clients_packs[1]
client_services = packs.dot(client_vector)

print('Minutos', 'Mensajes', 'Megabytes')
print(client_services)

Paquete del cliente
                
"Al volante"   2
"En el metro"  3

Minutos Mensajes Megabytes
[  55   19 4000]


Transponer matrices

In [45]:
x= np.array([[2,4,32],[8,3,3]])
x.T

array([[ 2,  8],
       [ 4,  3],
       [32,  3]])

#### Multiplicacion de Matrices
 
Para poder multiplicar matrices debemos considerar que `el numero de filas de a coincida con el número de columnas de b`. El número de columnas de la primera matriz debe coincidir con el número de filas de la segunda matriz.

In [17]:
import numpy as np

matriz1 = np.array(
    [[1,2],
	[1,2]])
matriz2 = np.array(
    [[3,4],
     [3,4]])

print( matriz1 @ matriz2 , end='\n\n')
print( matriz1.dot(matriz2), end='\n\n')
print( np.dot(matriz1, matriz2 ), end='\n\n')

print(matriz1 * matriz2)


# c11= 2, 6
# c12= 2, 6
# c21 = 4,8
# c22 = 4,8

# 9 12
# 9 12



[[ 9 12]
 [ 9 12]]

[[ 9 12]
 [ 9 12]]

[[ 9 12]
 [ 9 12]]

[[3 8]
 [3 8]]


In [4]:
import numpy as np

matriz1 = np.array(
    [[5, 3, -4, -2],
	[8, -1, 0, -3]])
matriz2 = np.array(
    [[1,4,0],
     [-5,3,7],
     [0,-9,5],
     [5,1,4]])

matriz1 @ matriz2
matriz1.dot(matriz2)


array([[-20,  63,  -7],
       [ -2,  26, -19]])


Roble y Pino ha recibido pedidos de muebles de varios lugares diferentes y necesitan saber las cantidades de los materiales que necesitan para cumplir con los pedidos. Como antes, la matriz manufacture muestra los materiales necesarios para cada uno de los diferentes tipos de muebles, donde las filas son los tipos de muebles (silla, banca y mesa) y las columnas son los materiales. Por ejemplo, para hacer una silla, necesitamos 0.2 metros de tabla, 1.2 metros de tubo de metal y 8 tornillos.

La matriz furniture muestra el número de cada mueble en los diferentes lugares: una cafetería, un comedor y un restaurante, donde las filas son los lugares y las columnas son los tipos de muebles. Por ejemplo, la cafetería necesita 12 sillas, 0 bancas y 3 mesas.

Encuentra la matriz venues_materials, que enumera los establecimientos por fila y los materiales para amueblarlos por columna. Muestra el resultado en pantalla (en precódigo).

Calcula la cantidad de materiales necesarios para la producción de muebles si el pedido se recibió de 18 cafeterías, 12 comedores y 7 restaurantes. Guarda este vector en la variable total_materials y muéstralo en la pantalla (en precódigo).

In [33]:
import numpy  as np
import pandas as pd

materials_names = ['Tabla', 'Tubos', 'Tornillos']
venues_names = ['Cafetería', 'Comedor', 'Restaurante']

manufacture = np.array([
    [0.2, 1.2, 8],    # materiales para silla
    [0.5, 0.8, 6],    # materiales para banco
    [0.8, 1.6, 8]])   # materiales para mesa

furniture = np.array([
    [12, 0, 3],   # Pedido de cafetería (silla, banca, mesa)
    [40, 2, 10],  # Pedido de comedor
    [60, 6, 18]]) # Pedido de restaurante

venues = [18, 12, 7]

In [34]:
pd.DataFrame(manufacture, columns=materials_names, index=['silla','mesa','banco'])

Tabla  Tubos  Tornillos
silla    0.2    1.2        8.0
mesa     0.5    0.8        6.0
banco    0.8    1.6        8.0

In [35]:
pd.DataFrame(furniture, columns=['silla','mesa','banco'], index=venues_names)

silla  mesa  banco
Cafetería       12     0      3
Comedor         40     2     10
Restaurante     60     6     18

In [36]:
#establefimientos en fila
#materiales por columna
total_materials = furniture @ manufacture

In [13]:
pd.DataFrame(total_materials, columns=materials_names, index=venues_names)

Tabla  Tubos  Tornillos
Cafetería      4.8   19.2      120.0
Comedor       17.0   65.6      412.0
Restaurante   29.4  105.6      660.0

In [44]:
total_materials @(venues) #Imprimiento el total de materiales

array([1156.8, 3977.2, 6416.4])

In [41]:
new_matrix = [] 

for i, row in enumerate(total_materials):
	new_matrix.append(row*venues[i])

In [45]:
pd.DataFrame(new_matrix, columns=materials_names , index=venues_names) 

Tabla  Tubos  Tornillos
Cafetería     86.4  345.6     2160.0
Comedor      204.0  787.2     4944.0
Restaurante  205.8  739.2     4620.0

In [26]:
np.array([2,4,5]) *3

array([ 6, 12, 15])

In [ ]:

venues_materials = manufacture.dot(furniture.T)  #[3,3][3,3]

print('Por el establecimiento')
print(pd.DataFrame(venues_materials, index=venues_names, columns=materials_names))
print()

venues = [18, 12, 7]

total_materials = venues_materials.T @ venues

print('Total')
print(pd.DataFrame([total_materials], index=[''], columns=materials_names))

## Matriz unitaria (o de identidad)

Ahora aprendamos sobre matrices identidad e inversas. Estos conceptos son importantes para derivar la función objetivo con la intención de minimizar el ECM.
`Una matriz identidad (también conocida como matriz unitaria) es una matriz cuadrada con unos a lo largo de la diagonal principal y ceros en el resto.`

Veamos una matriz identidad de 3×3.

In [9]:

import numpy as np
matriz_unit= np.array([[1,0,0],[0,1,0],[0,0,1]])

matriza = np.array([[3,4,6],[1,6,3],[8,5,5]])

matriza @matriz_unit

array([[3, 4, 6],
       [1, 6, 3],
       [8, 5, 5]])

El resultado de la matriz sería identico al multiplicarlo por una matriz unitaria (de identidad), incluso si se usan menos observaciones (filas) en la matriz

In [11]:

import numpy as np
matriz_unit= np.array([[1,0,0],[0,1,0],[0,0,1]])

matrizA = np.array([[3,4,6]])

matrizA @matriz_unit


array([[3, 4, 6]])

Incluso si multiplicas dos matrices de identidad, obtendrás el mismo resultado.

In [17]:

matriz_unit @ matriz_unit

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [16]:
matrizB = np.ones([3,3])
matrizB

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Matriz Inversa

La matriz inversa (denotada por −1) para una matriz cuadrada A es la matriz c`uyo producto con A es igual a la matriz identidad`. La multiplicación se puede realizar en cualquier orden. No todas las matrices tienen inversa, y las que la tienen se llaman matrices invertibles.

In [19]:
import numpy as np

# Definimos una matriz de ejemplo
matriz = np.array([[2, 1, -1],
                   [0, -1, 2],
                   [1, 1, 1]])

# Calculamos la inversa de la matriz
matriz_inversa = np.linalg.inv(matriz)

# Imprimimos la matriz original y su inversa
print("Matriz original:")
print(matriz)
print("\nMatriz inversa:")
print(matriz_inversa)

np.linalg.inv(matriz_unit)

Matriz original:
[[ 2  1 -1]
 [ 0 -1  2]
 [ 1  1  1]]

Matriz inversa:
[[ 0.6  0.4 -0.2]
 [-0.4 -0.6  0.8]
 [-0.2  0.2  0.4]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])