## Matriz


Una matriz es una tabla rectangular o tabla bidimensional que consta de m filas y n columnas (el tamaño se escribe como m x n). Las matrices generalmente se denotan con letras latinas mayúsculas, por ejemplo, A. Sus elementos están en minúsculas con doble índice a_ij, donde i es el número de fila y j es el número de columna.

#### Creando una matriz a partir de dos vectores


In [ ]:
import pandas as pd
import numpy as np

vector1= np.array([1,2,3])
vector2= np.array([4,5,6])

matrix = np.array([vector1 , vector2])
matrix

#### Crear una matriz a partir de un df

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'a': [120, 60, 75], 'b': [42, 154, 90],'c': [1344, 154, 2090] })
print(df)
matrix = df.values
matrix

     a    b     c
0  120   42  1344
1   60  154   154
2   75   90  2090


array([[ 120,   42, 1344],
       [  60,  154,  154],
       [  75,   90, 2090]], dtype=int64)

Otra operación útil que podríamos necesitar realizar es acceder a un elemento de la matriz. Usando la matriz A en el código anterior, el elemento a_ij se llama mediante A[i, j], donde la fila es i y la columna es j, enumeradas desde cero, de la misma forma que los índices de matriz.

Veamos esto en el siguiente ejemplo donde recuperamos el elemento de matriz 2090:

In [ ]:
matrix[2,2]

2090

In [ ]:
matrix[[0,2],:]

array([[ 120,   42, 1344],
       [  75,   90, 2090]], dtype=int64)

#### Atributos para matrices

In [ ]:
matrix.shape
matrix.argmax() #posicion de fila (vector) donde se encuentra el valor mas alto
matrix.argmin() #posicion de fila (vector) se encuentra el valor mas bajo
matrix.argsort() #ordena y devuelve los indices evaluando y ordenando los números por filas (es mas facil verlo en un df porque ve el valor mas bajo de una fila)
matrix.astype(float) #transforma los tipos de datos
matrix.cumsum() #suma cumulativa.
matrix.cumprod() # va multiplicando por cada valor en los vectores.
matrix.diagonal() # da los valores de las diagonales.
matrix.max() #valor maximo de la matriz
matrix.min() # valor minimo de la matriz
matrix.mean() # valor total promedio.
matrix.repeat(2) # Repite todos los valores.
matrix.prod() #producto de la multiplicacione de todos los elementos en la matriz
matrix.sum() #suma todo los valores
matrix.std() #obtiene la variacion std
matrix.transpose() #transpone los datos

### Operaciones con matrices.

#### Operaciones de matrices por un numero

In [ ]:
import numpy as np

matrix = np.array([
    [1, 2], 
    [3, 4]])

print(f' product \n{matrix * 2}', end='\n\n')
print(f' sum \n{matrix + 2}', end='\n\n')
print(f' rest \n{matrix - 2}', end='\n\n')

 product 
[[2 4]
 [6 8]]

 sum 
[[3 4]
 [5 6]]

 rest 
[[-1  0]
 [ 1  2]]



#### Operaciones de matrices con otras matrices.

In [ ]:
import numpy as np

matrix1 = np.array([
    [1, 2], 
    [3, 4]])

matrix2 = np.array([
    [5, 6], 
    [7, 8]])

print(f'product \n{np.multiply(matrix1, matrix2)}', end='\n\n') 
print(f'sum \n{matrix1 + matrix2}', end='\n') 
print(f'rest \n{matrix1 - matrix2}', end='\n')

product 
[[ 5 12]
 [21 32]]

sum 
[[ 6  8]
 [10 12]]
rest 
[[-4 -4]
 [-4 -4]]


In [ ]:
import numpy as np
import pandas as pd

services = ['Minutos', 'Mensajes', 'Megabytes']

monday = np.array([
    [10, 2, 72],
    [3, 5, 111],
    [15, 3, 50],
    [27, 0, 76],
    [7, 1, 85]])

tuesday = np.array([
    [33, 0, 108],
    [21, 5, 70],
    [15, 2, 15],
    [29, 6, 34],
    [2, 1, 146]])

wednesday = np.array([
    [16, 0, 20],
    [23, 5, 34],
    [5, 0, 159],
    [35, 1, 74],
    [5, 0, 15]])

thursday = np.array([
    [25, 1, 53],
    [15, 0, 26],
    [10, 0, 73],
    [18, 1, 24],
    [2, 2, 24]])

friday = np.array([
    [32, 0, 33],
    [4, 0, 135],
    [2, 2, 21],
    [18, 5, 56],
    [27, 2, 21]])

saturday = np.array([
    [28, 0, 123],
    [16, 5, 165],
    [10, 1, 12],
    [42, 4, 80],
    [18, 2, 20]])

sunday = np.array([
    [30, 4, 243],
    [18, 2, 23],
    [12, 2, 18],
    [23, 0, 65],
    [34, 0, 90]])

weekly = np.array(monday + tuesday + wednesday + thursday + friday + saturday + sunday)

print('En una semana')
print(pd.DataFrame(weekly, columns=services))
print()

## cuánto usa cada cliente los servicios en promedio por día
## crear una matris con todos los días

forecast = ((weekly / 7) * 30.4).astype(int)

print('Pronóstico para un mes')
print(pd.DataFrame(forecast, dtype=int, columns=services))

En una semana
   Minutos  Mensajes  Megabytes
0      174         7        652
1      100        22        564
2       69        10        348
3      192        17        409
4       95         8        401

Pronóstico para un mes
   Minutos  Mensajes  Megabytes
0      755        30       2831
1      434        95       2449
2      299        43       1511
3      833        73       1776
4      412        34       1741


#### Operacion de matrices por un vector

Para entender exactamente cómo se multiplica una matriz por un vector, primero debemos recordar que una matriz no es más que un conjunto de vectores de la misma longitud.

$$ 
\begin{matrix}a_{11} & a_{12} & \cdots & a_{1n} \\a_{21} & a_{22} & \cdots & a_{2n} \\\vdots & \vdots & \ddots & \vdots \\a_{m1} & a_{m2} & \cdots & a_{mn} \\\end{matrix}\begin{pmatrix}x_1 \\x_2 \\\vdots \\x_n \\\end{pmatrix}=\begin{pmatrix}a_{11}x_1 + a_{12}x_2 + \cdots + a_{1n}x_n \\a_{21}x_1 + a_{22}x_2 + \cdots  a_{2n}x_n \\\vdots \\a_{m1}x_1 + a_{m2}x_2 + \cdots + a_{mn}x_n \\\end{pmatrix}$$

Ya conocemos el uso del producto escalar para multiplicar un vector por otro. El mismo principio guía este proceso también. Para multiplicar una matriz por un vector, tomamos el producto escalar de cada fila y el vector, como puedes ver a continuación. El resultado es un nuevo vector. Sin embargo, presta atención: ya que estamos usando el producto escalar, es esencial que la longitud de cada fila de la matriz sea igual a la longitud del vector por el que multiplicamos.

La mejor parte es que NumPy puede encargarse de todo esto por nosotros. Todo lo que tenemos que hacer es llamar a dot(). Podemos hacer esto como una función independiente o como un método de nuestra matriz.

In [11]:
import numpy as np

matrix = np.array([
    [1,2,3],
    [4,5,6]])

vector = np.array([3,3,3])

# Funcion independiente, toma dos argumentos
print(np.dot(matrix,vector))

# Funcion de la matriz- solo necesita un argumento
print(matrix.dot(vector))

[18 45]
[18 45]
